### ISSUE TITLE
Feature suggestion - row totals

### ISSUE THREAD

**Issue by wieshka** [flrs/visavail#12]
It would be nice to have last column per row which shows per row totals, for example, with default categories, _97,89 % off time available_.

In case of custom categories, per category percentage could be shown.

Optionally, a tables average availability could be shown on bottom of table.

**Comment by flrs** [comment]
Hey @wieshka, the row totals feature is an interesting thought. However, this would mean that the library takes a further step into data analysis, and not so much visualization.

I have thought about the row totals a little and I think that the row total display depends a lot on the use case. While one might be interested in knowing whether something is available 80% or 90%, others might chase decimal, thus 99.95% and 99.98% make a big difference. There needs to be some kind of scale-aware display that adjusts the decimals and maybe even the unit.

Also, the system only works for a binary display, for example when you have "on" and "off". However, in some use cases you have an intentional standby and might want to add that state. Then, what do you display? How do you calculate?

To be honest, while I think the feature is nice, I do not think it belongs to this library since it is more data analysis than data visualization. Do you agree?

**Comment by tanganellilore** [comment]
Hi @wieshka,

I'm agree with Flrs and probably this type of calculation depends a lot in base of use case.
I close this issue because not updated from 2 years and half.

Honestly i think that this type of calculation was provided by custom algorith or specific backend tahth can be process data anc calulcate the %.
