### ISSUE TITLE
Large dataset

### ISSUE THREAD

**Issue by nomailme** [flrs/visavail#15]
Hi. I'm thinking about using your awesome library. The question is how large can a dataset be. I'm planning to load about 30000 vertices.
I know the question is vague, but what was the largest dataset that you managed to render on the screen. Thanks

**Comment by flrs** [comment]
Hi @nomailme!

It is good to hear that you like the library and are interested in using it in your project.

I have not tried to load such a large data set. I think the maximum size I tried was about 300 vertices. However, this was in no way related to test the limits of the library. Why don't you try and let us know what happens when you try to render that many vertices?

To limit resource use, there is a trick I can think of: Use the resolution of the target display to find out which minimum time interval you are able to display. For example, any time intervals that would result in a width smaller than a pixel would not show up on a computer screen. Then, you can use that information to filter your data before sending it to Visavail.js.

Let us know about your progress!

**Comment by nomailme** [comment]
Thank you @flrs! We basically did some preprocessing of this large dataset and were able to reduce dataset to about 200 verticies and at this point it's been working like a charm. What we did was skipping duplicate entries with different timestamps and keeping only changed values. Maybe in the future we will have to somehow limit time range but at this point I see no use of that. Thank you for your awesome library!

**Comment by flrs** [comment]
@nomailme, I am happy to see that you made it work!
