### ISSUE TITLE
Weekly Report but range is wrong

### ISSUE THREAD

**Issue by ijunaid8989** [flrs/visavail#6]
First: Thanks a lot for your work its really very awesome and helpful.

Now :)

![image](https://cloud.githubusercontent.com/assets/13561999/21469922/a40ffb34-ca91-11e6-8828-4a080c5ccf12.png)

I am trying to create multiple weekly report, the range should be from 12/18/2016 10:26:14 AM to 12/25/2017 10:26:14 AM

But its from from 12/18/2016 10:26:14 AM to 1/1/2017 10:26:14 AM ??

Even the range in data is correct as 
```
{"measure":"10 11 Front Ext","interval_s":604800,"data":[["2016-12-18 10:26:14",1],["2016-12-25 10:26:14",1]]}
```
Where my data was empty I have set it to starting of week to ending of week. but its setting the ending week date time to 1-1-2017..?

**Comment by ijunaid8989** [comment]
Also this gives strange results

https://gist.github.com/ijunaid8088/f54da68e6fd5e584e477e8360d65a9ad

**Comment by flrs** [comment]
@ijunaid8088, thank you for your nice feedback! I had a look at your questions.

The reason that you are getting the date range to 1/1/2017 10:26:14 AM is because you specified `"interval_s":604800`. 604800 seconds/60/60/24 = 7 days, so you would expect the date range to go up to `"2016-12-25 10:26:14"` + 7 days = 1/1/2017 10:26:14 AM.

The rationale for this behavior is that a data point is expected to cover a time range. For example, imagine you want to display the data availability of some measure that is taken once per week. In the Visavail.js chart you would expect that the horizontal bar based on that data point covers one entire week. The length of that bar, or the interval that a data point covers, is set by the parameter `interval_s`.

In your case I suggest to specify discrete time ranges. This goes by the name "Data With Dates and Times", see [here](https://github.com/flrs/visavail#data-with-dates-and-times). Your data would then look like `{"measure":"10 11 Front Ext", "data":[["2016-12-18 10:26:14",1, "2016-12-25 10:26:14"]]}`.

**Comment by flrs** [comment]
As to https://gist.github.com/ijunaid8088/f54da68e6fd5e584e477e8360d65a9ad I would change your dataset variable to something like this:
```html
<script type="text/javascript">
    var dataset = [
        {
            "measure":"Staffords Waterford VH",
            "data":[
                ["2016-12-18 00:25:20",1,"2016-12-19 00:25:20"],
                ["2016-12-19 00:25:20",0,"2016-12-19 00:26:18"],
                ["2016-12-19 00:26:18",1,"2016-12-19 05:50:21"],
                ["2016-12-19 05:50:21",0,"2016-12-19 05:51:19"],
                ["2016-12-19 05:51:19",1,"2016-12-20 05:25:46"]
            ]
        }
    ];
</script>
```
